[build]
  # If you are using Vite (which is standard now) use "dist"
  # If you are using Create React App, change "dist" to "build"
  publish = "dist"
  command = "npm run build"

# This part fixes 404 errors when refreshing pages
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
